version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 8
    groups:
      npm-prod-patch:
        applies-to: version-updates
        dependency-type: production
        patterns:
          - '*'
        update-types:
          - patch

      npm-prod-minor:
        applies-to: version-updates
        dependency-type: production
        patterns:
          - '*'
        update-types:
          - minor

      npm-dev-patch:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - '*'
        update-types:
          - patch

      npm-dev-minor:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - '*'
        update-types:
          - minor

      security-prod:
        applies-to: security-updates
        dependency-type: production
        patterns:
          - '*'
        update-types:
          - patch
          - minor

      security-dev:
        applies-to: security-updates
        dependency-type: development
        patterns:
          - '*'
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 4
    groups:
      github-actions-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - patch

      github-actions-minor:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor

      security-actions:
        applies-to: security-updates
        patterns:
          - '*'
        update-types:
          - patch
          - minor
