name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: release-build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    if: "contains(github.event.head_commit.message, 'chore: release')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Use Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Commit generated build
        id: commit
        run: |
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git config --global core.autocrlf true
          git config --global core.safecrlf false
          git add .
          git diff --cached --quiet && exit 0
          git commit -m "chore: ci build"
          echo "created=true" >> "$GITHUB_OUTPUT"

      - name: Push generated build
        if: steps.commit.outputs.created == 'true'
        run: git push origin HEAD:${{ github.ref_name }}

      - name: Log
        if: steps.commit.outputs.created != 'true'
        run: echo Nothing to commit.
